name: 🔎 Indexación en motores de búsqueda 

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  wait-for-vercel-deployment:
    name: 🔼 Esperar el deploy en Vercel
    if: github.repository == 'TeenBiscuits/Pasame-Codigo'
    runs-on: ubuntu-latest
    steps:
      - name: ⌛ Espera 100s
        run: sleep 100s
        shell: bash
      - name: ⌛ Esperar deploy
        # tj-actions
        # MIT
        # https://github.com/tj-actions/vercel-wait
        uses: tj-actions/vercel-wait@v1
        with:
          project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          token:  ${{ secrets.VERCEL_TOKEN }}
          sha: ${{ github.sha }}
          timeout: ''

  indexnow:
    name: 🔎 Bing IndexNow
    if: github.repository == 'TeenBiscuits/Pasame-Codigo'
    needs: [wait-for-vercel-deployment]
    runs-on: ubuntu-latest
    steps:
      - name: ⬆️ Subir Sitemap
        # Bojie Yang
        # MIT
        # https://github.com/bojieyang/indexnow-action
        uses: bojieyang/indexnow-action@v2
        with:
          sitemap-location: 'https://pc.pablopl.dev/sitemap-0.xml'
          key: ${{ secrets.INDEXNOW_KEY }}
          key-location: 'https://pc.pablopl.dev/${{ secrets.INDEXNOW_KEY }}.txt'
          endpoint: www.bing.com # Es el default
          failure-strategy: error

  google-indexing:
    name: 🔎 Google Index
    if: github.repository == 'TeenBiscuits/Pasame-Codigo'
    needs: [wait-for-vercel-deployment]
    runs-on: ubuntu-latest
    steps:
      - name: ⬆️ Subir Urls
        # Robin Genz
        # MIT
        # https://github.com/robingenz/google-indexing-action
        uses: robingenz/action-google-indexing@v1.0.1
        with:
          siteUrl: 'pc.pablopl.dev'
          gcpServiceAccountKey: ${{ secrets.GCP_SA_KEY }}